---
title: "AidData"
author: "Alexandra Norris"
date: "10/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

```{r}

# load in data on aid projects: https://www.aiddata.org/data/aiddata-core-research-release-level-1-3-1

aid <- read_csv("AidDataCore_ResearchRelease_Level1_v3.1 (2)/AidDataCoreFull_ResearchRelease_Level1_v3.1.csv")

# list key disaster recovery related words to filter because there is no simple way to filter
# keywords <- c("DISASTER","RECOVERY","RELIEF")

# filter for short descriptions that include the key words
# disaster <- aid[grep(paste0(keywords, collapse = "|"), aid$short_description),]

```

```{r}

library(lubridate)

aid2 <- aid %>%
  # filter for only projects that involve post-disaster rebuilding
  filter(aiddata_sector_name == "Reconstruction relief") %>%
  # filter(crs_purpose_name == "Reconstruction relief") %>%
  # create a "length of project" variable
  mutate(start_date_aid = as.Date.character(start_date, format = "%d/%m/%Y")) %>%
  mutate(end_date_aid = as.Date.character(end_date, format = "%d/%m/%Y")) %>%
  mutate(project_length = end_date_aid - start_date_aid) %>%
  # create a year, month, and day variable for merging
  mutate(start_month_aid = substr(start_date_aid, 6,7)) %>%
  mutate(start_day_aid = substr(start_date_aid, 9,10)) %>%
  mutate(project_length = as.numeric(project_length)) %>%
  # omit all rows that don't have a length
  filter(!is.na(project_length)) %>%
  filter(project_length >= 0) %>%
  mutate(log_proj = log(project_length+1)) %>%
  mutate(iso2 = recipient_iso) %>%
  dplyr::select(aiddata_id, aiddata_2_id, title, iso2, recipient, year, donor, start_date_aid, end_date_aid, start_month_aid, start_day_aid, project_length, commitment_amount_usd_constant, commitment_amount_usd_current, log_proj) %>%
  filter(!is.na(iso2)) 


# 
# dis %>%
#   select(aiddata_id, donor, donor_iso, recipient, recipient_iso, implementing_agency, financing_agency, title, short_description, long_description, aiddata_activity_names, aiddata_purpose_name, crs_sector_name, crs_purpose_name, start_date, end_date, commitment_date, project_length, commitment_amount_usd_constant) %>%
#   arrange(project_length)
# 
# # find most frequent donors
# 
# dis %>%
#   select(donor, financing_agency) %>%
#   group_by(donor, financing_agency) %>%
#   count() %>%
#   arrange(desc(n))
# 
# # TOP: 
# # AID:US
# # MFA:Netherlands
# # SDC:Switzerland - online database
# # DOD:US, AG:Spain, MFA:Norway, DFI:Ireland
# 
# # for disasters without a start date I can use the day of the disaster as a proxy for the beginning of aid
# 
# 
# test <- aid %>%
#   filter(aiddata_sector_name == "Reconstruction relief") %>%
#   group_by(aiddata_purpose_name) %>%
#   count()
#   select(aiddata_purpose_name) %>%distinct()
```

```{r}
# read in the project performance data

project <- read_csv("PPD2_Jan_21_2022.csv") %>%
  filter(countryname_COW != "Multinational") %>%
  filter(aiddata_sectorname == "RECONSTRUCTION RELIEF") %>%
  dplyr::select(donor, countryname_COW, project_duration, aid_type, startyear, six_overall_rating) %>%
  rename(recipient = countryname_COW) %>%
  rename(year = startyear) %>%
  filter(!is.na(six_overall_rating)) %>%
  mutate(satisfaction = ifelse(six_overall_rating==1,6,ifelse(six_overall_rating==2,5,ifelse(six_overall_rating==3,4,ifelse(six_overall_rating==4,3,ifelse(six_overall_rating==5,2,1))))))

```



```{r}

# run an analysis of aid project lengths for disaster reconstruction without controlling for disaster

# merge with the capacity data

# read in EMDAT data and then merge it with the aid data
dis_cap <- read_csv("chapter1_cleaned.csv") %>%
  mutate(year = start_year) %>%
  mutate(recipient = country) %>%
  dplyr::select(iso2, recipient, capacity, disaster_type, disaster_subtype, location, year, start_month, start_day, total_deaths, death_rate, log_death, v2clrspct, milpercap, ape1, gdp_per_cap, log_gdp_percap, disaster_mag)

capacity <- dis_cap %>%
  dplyr::select(iso2, recipient, year, start_month, start_day, capacity, disaster_type, disaster_mag, log_gdp_percap, v2clrspct, milpercap, ape1) %>%
  filter(!is.na(iso2)) %>%
  filter(disaster_type != c("Drought", "Epidemic","Extreme temperature"))

# merge by year, 

merged_data_90 <- merge(aid2, capacity, by = c("year", "iso2")) %>%
  # create exact disaster date
  mutate(disaster_date = make_date(year = year, month = start_month, day = start_day)) %>%
  # create a thing to tell when the project happened relative to the disaster
  mutate(after = ifelse(disaster_date > start_date_aid,0,1)) %>%
  filter(after == 1) %>%
  mutate(how_much_after = start_date_aid - disaster_date) %>%
  filter(how_much_after <=90) %>%
  filter(!is.na(project_length)) %>%
  filter(project_length >=0) %>%
  mutate(log_length = log(project_length+1))

merged_data_31 <- merge(aid2, capacity, by = c("year", "iso2")) %>%
  # create exact disaster date
  mutate(disaster_date = make_date(year = year, month = start_month, day = start_day)) %>%
  # create a thing to tell when the project happened relative to the disaster
  mutate(after = ifelse(disaster_date > start_date_aid,0,1)) %>%
  filter(after == 1) %>%
  mutate(how_much_after = start_date_aid - disaster_date) %>%
  filter(how_much_after <=31) %>%
  filter(!is.na(project_length)) %>%
  filter(project_length >=0) %>%
  mutate(log_length = log(project_length+1))

merged_data_13 <- merge(aid2, capacity, by = c("year", "iso2")) %>%
  # create exact disaster date
  mutate(disaster_date = make_date(year = year, month = start_month, day = start_day)) %>%
  # create a thing to tell when the project happened relative to the disaster
  mutate(after = ifelse(disaster_date > start_date_aid,0,1)) %>%
  filter(after == 1) %>%
  mutate(how_much_after = start_date_aid - disaster_date) %>%
  filter(how_much_after <=13) %>%
  filter(!is.na(project_length)) %>%
  filter(project_length >=0) %>%
  mutate(log_length = log(project_length+1))


# larger dataset without emdat
small_data <- merge(aid2, capacity) %>%
  filter(project_length >= 0)

# no-emdat data but with project satisfaction
project_full <- merge(project, capacity, all.x = TRUE, all.y = FALSE) %>%
  filter(project_duration >= 0)

```


```{r}
library(MASS)

# create a model looking at disaster data 
dis_fit <- glm.nb(project_length ~ capacity + log_gdp_percap + donor, data = small_data)
dis_fit_dis90 <- glm.nb(project_length ~ capacity + log_gdp_percap + donor + disaster_type, data = merged_data_90)
dis_fit_mag90 <- glm.nb(project_length ~ capacity + log_gdp_percap + donor + disaster_type + disaster_mag, data = merged_data_90)

# one month data
dis_fit_dis31 <- glm.nb(project_length ~ capacity + log_gdp_percap + donor + disaster_type, data = merged_data_31)
dis_fit_mag31 <- glm.nb(project_length ~ capacity + log_gdp_percap + donor + disaster_type + disaster_mag, data = merged_data_31)

# two weeks
dis_fit_dis14 <- glm.nb(project_length ~ capacity + log_gdp_percap + donor + disaster_type, data = merged_data_13)
dis_fit_mag14 <- glm.nb(project_length ~ capacity + log_gdp_percap + donor + disaster_type + disaster_mag, data = merged_data_13)

# do the same as above but for the log project

dis_fit_log <- glm(log_proj ~ capacity + log_gdp_percap + donor, data = small_data)

dis_log14 <- glm(log_proj ~ capacity + log_gdp_percap + donor + disaster_type, data = merged_data_13)
mag_log14<- glm(log_proj ~ capacity + log_gdp_percap + donor + disaster_type + disaster_mag, data = merged_data_13)
dis_log31 <- glm(log_proj ~ capacity + log_gdp_percap + donor + disaster_type, data = merged_data_31)
mag_log31<- glm(log_proj ~ capacity + log_gdp_percap + donor + disaster_type + disaster_mag, data = merged_data_31)
dis_log90 <- glm(log_proj ~ capacity + log_gdp_percap + donor + disaster_type, data = merged_data_90)
mag_log90 <- glm(log_proj ~ capacity + log_gdp_percap + donor + disaster_type + disaster_mag, data = merged_data_90)


# MAKE TWO TABLES - 1 for medium term and the other for appendix with short and long term
cat(stargazer::stargazer(dis_fit, dis_fit_dis31, dis_fit_mag31, dis_fit_log, dis_log31, mag_log31,
                     dep.var.labels=c("Project Length", "ln(Project Length)"),
                     column.labels = c("All Projects", "Matched Data", "All Projects", "Matched Data"),
                     column.separate = c(1,2,1,2),
                     keep=c("capacity","log_gdp_percap","disaster_mag"),
                     covariate.labels=c("State Capacity", "ln(GDP Per Capita)", "Disaster Magnitude"),
                     header = FALSE), file = "Ch2_Exhibits/all_data_cap.tex")
#APPENDIX TABLE
cat(stargazer::stargazer(dis_fit_dis90, dis_fit_mag90, dis_fit_dis14, dis_fit_mag14, dis_log90, mag_log90,dis_log14, mag_log14,
                     dep.var.labels=c("Project Length", "ln(Project Length)"),
                     column.labels = c("90-day Match", "14-day Match","90-day Match", "14-day Match"),
                     column.separate = c(2,2,2,2),
                     keep=c("capacity","log_gdp_percap","disaster_mag"),
                     covariate.labels=c("State Capacity", "ln(GDP Per Capita)", "Disaster Magnitude"),
                     header = FALSE), file = "Ch2_Exhibits/14-90cap_appendix.tex")


# project quality

qual <- lm(satisfaction ~ capacity + log_gdp_percap + donor, data = project_full)

qual3 <- lm(satisfaction ~ v2clrspct + milpercap + ape1 + log_gdp_percap + donor, data = project_full)

# make table
cat(stargazer::stargazer(qual, 
                         dep.var.labels=c("Project Satisfaction"),
                         keep = c("v2clrspct","milpercap","ape1", "log_gdp_percap"),
                         covariate.labels = c("Adaptive Capacity","Coercive Capacity","Extractive Capacity","ln(GDP Per Capita"),
                         header = FALSE), 
    file ="Ch2_Exhibits/cap_breakdown_quality.tex")

# make table
cat(stargazer::stargazer(qual,qual3, 
                         dep.var.labels=c("Project Satisfaction"),
                         keep = c("capacity", "v2clrspct","milpercap","ape1", "log_gdp_percap", "log_gdp_percap"),
                         covariate.labels = c("State Capacity","Adaptive Capacity","Coercive Capacity","Extractive Capacity","ln(GDP Per Capita"),
                         header = FALSE), file ="Ch2_Exhibits/quality.tex")

```

```{r}

######## REPEAT ABOVE BUT FOR DIFFERENT VERSIONS OF STATE CAPACITY

library(MASS)

# create a model looking at disaster data 
dis_fit <- glm.nb(project_length ~ v2clrspct + milpercap + ape1 + log_gdp_percap + donor, data = small_data)
dis_fit_dis90 <- glm.nb(project_length ~ v2clrspct + milpercap + ape1 + log_gdp_percap + donor + disaster_type, data = merged_data_90)
dis_fit_mag90 <- glm.nb(project_length ~ v2clrspct + milpercap + ape1 + log_gdp_percap + donor + disaster_type + disaster_mag, data = merged_data_90)

# one month data
dis_fit_dis31 <- glm.nb(project_length ~ v2clrspct + milpercap + ape1 + log_gdp_percap + donor + disaster_type, data = merged_data_31)
dis_fit_mag31 <- glm.nb(project_length ~ v2clrspct + milpercap + ape1 + log_gdp_percap + donor + disaster_type + disaster_mag, data = merged_data_31)

# two weeks
dis_fit_dis14 <- glm.nb(project_length ~ v2clrspct + milpercap + ape1 + log_gdp_percap + donor + disaster_type, data = merged_data_13)
dis_fit_mag14 <- glm.nb(project_length ~ v2clrspct + milpercap + ape1 + log_gdp_percap + donor + disaster_type + disaster_mag, data = merged_data_13)

# do the same as above but for the log project

dis_fit_log <- glm(log_proj ~ v2clrspct + milpercap + ape1 + log_gdp_percap + donor, data = small_data)

dis_log14 <- glm(log_proj ~ v2clrspct + milpercap + ape1 + log_gdp_percap + donor + disaster_type, data = merged_data_13)
mag_log14<- glm(log_proj ~ v2clrspct + milpercap + ape1 + log_gdp_percap + donor + disaster_type + disaster_mag, data = merged_data_13)

dis_log31 <- glm(log_proj ~ v2clrspct + milpercap + ape1 + log_gdp_percap + donor + disaster_type, data = merged_data_31)
mag_log31<- glm(log_proj ~ v2clrspct + milpercap + ape1 + log_gdp_percap + donor + disaster_type + disaster_mag, data = merged_data_31)

dis_log90 <- glm(log_proj ~ v2clrspct + milpercap + ape1 + log_gdp_percap + donor + disaster_type, data = merged_data_90)
mag_log90 <- glm(log_proj ~ v2clrspct + milpercap + ape1 + log_gdp_percap + donor + disaster_type + disaster_mag, data = merged_data_90)


# MAKE TWO TABLES - 1 for medium term and the other for appendix with short and long term
cat(stargazer::stargazer(dis_fit, dis_fit_dis31, dis_fit_mag31, dis_fit_log, dis_log31, mag_log31,
                     dep.var.labels=c("Project Length", "ln(Project Length)"),
                     column.labels = c("All Projects", "Matched Data", "All Projects", "Matched Data"),
                     column.separate = c(1,2,1,2),
                     keep=c("v2clrspct", "milpercap","ape1","log_gdp_percap","disaster_mag"),
                      covariate.labels=c("Adaptive Capacity","Coercive Capacity","Extractive Capacity", "GDP Per Capita", "Disaster Magnitude"),
                     header = FALSE), file = "Ch2_Exhibits/3cap.tex")
#APPENDIX TABLE
cat(stargazer::stargazer(dis_fit_dis90, dis_fit_mag90, dis_fit_dis14, dis_fit_mag14, dis_log90, mag_log90,dis_log14, mag_log14,
                     dep.var.labels=c("Project Length", "ln(Project Length)"),
                     column.labels = c("90-day Match", "14-day Match","90-day Match", "14-day Match"),
                     column.separate = c(2,2,2,2),
                     keep=c("v2clrspct", "milpercap","ape1","log_gdp_percap","disaster_mag"),
                     covariate.labels=c("Adaptive Capacity","Coercive Capacity","Extractive Capacity", "GDP Per Capita", "Disaster Magnitude"),
                     header = FALSE, type="text"), file = "Ch2_Exhibits/14-90cap_3types_appendix.tex")



```

```{r}
# identify top 5 donors
small_data %>%
  dplyr::select(donor) %>%
  group_by(donor) %>%
  count() %>%
  arrange(desc(n))

small_data <- small_data %>%
  mutate(donor = relevel(factor(donor), ref = "United States"))

donor_fit_log <- glm(log_proj ~ donor + recipient, data = small_data)
donor_fit <- glm.nb(project_length ~ donor + recipient, data = small_data)

# create one with donors featured
cat(stargazer::stargazer(donor_fit,donor_fit_log,
                     dep.var.labels=c("Project Length","ln(Project Length)"),
                     keep=c("donorAustria", "donorUnited Kingdom", "donorNorway","donorSpain","donorSwitzerland"),
                     covariate.labels=c("Austria","Norway", "Spain","Switzerland", "United Kingdom"),
                     header = FALSE), file = "Ch2_Exhibits/donors.tex")
```


