---
date: "1/18/2022"
geometry: "left=2in,right=1in,top=1in,bottom=1in"
output:
  pdf_document:
    extra_dependencies: float
# link_citations: yes
header-includes: \usepackage{setspace}\doublespacing\setlength{\parindent}{4em}\setlength{\parskip}{0em}
#bibliography: references.bib
---

```{r setup, include=FALSE}


# The below code creates a bibliography and allows for the tables and figures to
# be placed where I want them to be

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")
knitr::write_bib(c("base", "tinytex", "knitr", "kableExtra", "latexpdf", "readtext", "utils", "stargazer", "tidyverse", "sandwich", "lfe", "grid", "RColorBrewer", "rgdal", "rgeos", "maptools", "seg", "splancs", "gridExtra"), "bibliography.bib", width = 60)

# load r packages

library(tinytex)
library(knitr)
library(kableExtra)
library(latexpdf)
library(readtext)
library(utils)
library(bookdown)

library(janitor)
library(tidyverse)
#
# # need to load latex package "dcolumn" to allow latex tables to run and package
# # "float" to place tables and figures where I want them to go
#
usepackage_latex("dcolumn")
usepackage_latex("float")

```

# Adaptive Capacity Chapter

This chapter focuses on the concept of adaptive capacity, a measure of whether a community did indeed "build back better". As explained in the theory chapter, adaptive capacity is defined as a community's ability to rebuild in a way that mitigates future risk to similar disasters[@gallopin2006linkages]. While seemingly simple, adaptive capacity relies on four key mechanisms: the ability to assess damages and identify weak points, the ability to finance disaster-safe rebuilding, buy-in and cooperation from stakeholders, and the ability of people to migrate to safer areas if they so wish. Adaptive capacity serves as a natural ending point of the empirical section of this thesis, after having interpreted the short-term relationship between disaster-related deaths and state capacity and length of rebuilding or "resilience" and state capacity, whether safer-practices or better outcomes come as a result of this is an important thing to measure. There is much literature on the idea of natural disaster-related "creative destruction" or the idea that the destruction caused by natural disasters can actually spur economic growth[@crespo2008natural]. While economic growth in the aftermath of natural disasters is important, this chapter explores adaptive capacity as it relates to differences in disaster-related deaths for communities that have experienced multiple disasters. I measure adaptive capacity by looking at the difference in disaster-related deaths between the first and subsequent disaster, and the role that state capacity plays in this relationship. As a robustness check, I measure total deaths as my outcome variable and compare outcomes for communities that have experienced a subsequent disaster to those that did not.

In the following pages, I will explain the data sources that I use to test my hypotheses, describe in-depth the methods that I use for my analysis and the justifications for using them, and finally, present the results of my analyses.

## Explanation of Data Sources and Measures

To test my hypothesis that greater state capacity is associated with greater adaptive capacity, I rely on the two datasets used for the analyses in Chapter 1: the EM-DAT disaster dataset and the @hanson2013leviathan measure of state capacity and its components. The EM-DAT data includes information on the specific location of a natural disaster, the type of disaster, the severity of the disaster, the number of deaths that can be attributed to the disaster, and the total economic damages that result from the disaster. The EM-DAT data spans between 1960 and the present, and includes over 15,000 disasters. Important for this analysis, while the EM-DAT data includes a variable for the province-level (administrative 1) and even village level (administrative 2) of destruction in some cases, it also includes a broadly-defined "location" variable which chooses the appropriate "name of a city, village, department, province, state, or district"[@emdat] that is appropriate for the disaster. This broadly defined location variable will be central for this analysis. I chose the location variable to denote the place of the disaster -- over the province, or the country --- because the variable is flexible. Different disasters affect different size areas and because this chapter focuses on looking at the relationship between national-level state capacity indicators and sub national disaster outcomes, it is not important whether a disaster struck a particular province, but it is important to know whether a disaster struck the same area twice, regardless of that area's size. Using the broadly defined location variable allows for the location to fit the disaster and for similar disasters impacting the same area to be compared. Because the EM-DAT data spans such a long time-period, I am able to find a number of locations that have experienced more than one disaster in this time period. Important to note, I recognize that 1960 is not year 0 and that communities may have experienced disasters that they have learned and adapted from pre 1960, but given the large size of this dataset and the fact that communities can continue to learn and adapt from subsequent disasters I believe that this is a valid measurement. 

Adaptive capacity indicates whether a given location did indeed "build back better". To measure this, I focus on the differences in outcomes between places experiencing a disaster for the first time and those experiencing a subsequent disaster. Like in Chapter 1, I focus on three main outcome variables: log disaster deaths, gross disaster deaths, and the deadliness of a disaster. As defined in Chapter 1, deadliness is the ratio of deaths to the number of people affected by the disaster - it indicates how deadly a disaster was for those who experienced it. The total deaths variable includes the number of people who lost their lives as a result of the disaster an the number of missing people (who are presumed dead). The log death variable is simply the log of the total death variable. Because the number of deaths is skewed towards zero and has a large variance, observing the variable in its log form allows the data to fit a model better so that the relationship between deaths and state capacity is clearer. Additionally, observing deaths in their gross form allows for the understanding of the real-life implications of state capacity on people's lives. Finally, while the EM-DAT dataset does include an estimate of the economic damages caused by a disaster, I choose not to use this as a means to measure adaptive capacity for two main reasons: 1) Property values after reconstruction could be greater than previously, meaning that a disaster with a similar or even lesser level of destruction could be classified as worse; and 2) A community that never chose to rebuild may experience very few economic losses if hit by a second disaster but that doesn't mean that the consequences were not dire for the people living there. The number of people who dies from and are affected by disasters are much more objective measures.
<!-- The value is based off of knowledge about the population of a given area and the number of homes destroyed. Finally, the total estimated damages variable includes the value of the economic losses and property damage that can be attributed both directly and indirectly to the disaster. The damages are measured in US dollars in the value of the year when the disaster occurred. To allow for cross-temporal comparisons and to account for inflation, I create a present-day (2021) value of economic losses variable using CPI data from the Bureau of Labor and Statistics. -->

Again, like in the first empirical chapter, I use the @hanson2013leviathan dataset to measure state capacity and its three components ---  administrative capacity, coercive capacity, and extractive capacity. As explained previously: administrative capacity relates to the strength of a country's bureaucracy, and is measured by the "Bureaucratic Quality" metric which indicates the strength of a nation's bureaucratic institutions on a scale of 1 to 4 with 4 indicating high reliability and distance from politics. Coercive capacity is a nation's ability to control its population, and is estimated using the Military personnel percapita variable which indicates the number of military-affiliated people per 1000 residents. Finally, extractive capacity indicates a country's ability to extract revenue from its people and territory, and is measured using the Absolute Political Extraction (APE) variable. This variable measures tax, mining, and export revenue relative to GDP and is displayed as a rate. The greater the value, the greater the extractive capacity of the nation. Importantly, to eliminate reverse causality, I "lag" all of the state capacity indicators, meaning that I reference the state capacity of the year prior to the disaster. This prevents any disaster-related changes to state capacity that could happen impacting my analysis.


# Methods

To explore the relationship between state capacity and adaptive capacity I first need to create my adaptive capacity measure. I do this by grouping my disaster and state capacity data on the basis of country, location, and disaster type. I then arrange the disaster data according to date within the groups and through referencing the previous disaster, am able to create three new variables: previous log deaths, previous total deaths, and previous deadliness. With these three new variables, I am then able to subtract the previous disaster values from the subsequent disaster values, creating a difference variable. Because of the variation in total deaths, I standardize this variable by dividing the difference by the initial death count --- the equation used to do this can be seen below. Because I subtract previous disaster values from subsequent ones, positive differences indicate that there was an increase in deaths during the subsequent disaster. In addition to the adaptive capacity measures, using this grouping, I create additional variables indicating how many times this location was hit by a certain disaster, how long was the time period between disasters, and a binary variable indicating whether the location has been hit before. 

$$Total\  Death \ = \frac{Subsequent\ Disaster\ Deaths - Previous\ Disaster\ Deaths}{Previous\ Disaster\ Deaths}$$
With this newly created measure of adaptive capacity, I can analyze the relationship between state capacity and adaptive capacity. The following sections explain the two techniques I use to observe this relationship: 1) standard regressions to explain these new difference variables, and 2) a robustness check in which I solely observe locations that experience multiple disasters, and the relationship between disaster-related deaths and whether this was the location's first or subsequent disaster.

## Measuring Adaptive Capacity

I explore the relationship between state capacity and each of the three measures of adaptive capacity through the use of the following linear model:

$$Adaptive\ Capacity\ Measure = \beta_0 +  \beta_1 *State\ Capacity + \beta_2*(Time\ Since\ Previous\ Disaster)^2 + \beta_3* Disaster\ Count + \beta_4*GDP\ per\ capita$$
The above model uses state capacity, the time since the previous disaster, how many disasters like this have there been, and GDP per capita to explain variation in the three adaptive capacity measures. Importantly, I include the "time since previous disaster" variable to measure the time between disasters and to account for the fact that time is a crucial component of "building back better". I square this variable because it is rational to assume that the relationship between time between disasters and disaster-related deaths is curvilinear or s-shaped, meaning that there likely will be larger effects in the medium-term as opposed to the short and very long terms. For instance, communities that experience two disasters in quick succession will likely have not recovered from the initial disaster and have not had a chance to rebuild, meaning that the relationship between state capacity and adaptive capacity will be weaker here. Similarly, if a location is hit by the same disaster but with a long period of time in the meantime, the memory of the initial disaster may have become so distant that disaster-safe practices are no longer a priority. Through squaring the "time since previous disaster" variable, I will be able to use a linear model to more accurately gague it's affects on adaptive capacity. Additionally, the disaster count variable is also included as a control to gague whether experiencing disasters repeatedly increases adaptive capacity. Finally, GDP per capita is included to account for financial differences between nations. Important to note, the disaster magnitude variable is not included in this model. This is because for the multiple-disaster data, there were a large number of NA values, meaning that including the variable would result in considerable data loss. A robustness check using the variable is included in the appendix.

## Robustness Check

As a robustness check of the above measure adaptive capacity, I will use the same models used in Chapter 1 but with the added variable indicating whether or not a location had previously experienced a similar disaster. The following estimation equations indicate the models used to estimate the relationship between having experienced a previous disaster, state capacity and the three key outcome variables.

$$Outcome\ Variable = \beta_0 + \beta_1*Capacity + \beta_2*Previous \ Disaster + \beta_3*Capacity*Previous \ Disaster + \beta_4*Disaster\ Type + \beta_5*Magnitude + \beta_6*GDP \ percapita$$
Because the three outcome variables have different properties --- total deaths is a count variable while deadliness is a ratio, and log deaths is a log --- I need to use different models to measure the relationships. As I did in Chapter 1, I use linear models to measure log deaths and deadliness, and a negative binomial model to measure total deaths. In addition to the broad state capacity variable, I am also interested in observing the three sub-categories of state capacity and how they interact with the previous disaster variable. Using the same model above, I substitute in the three different state capacity varaiable for state capacity, interacting each of them with whether or not a location previously experienced a disaster.

Importantly, if a community is hit by multiple disasters in rapid succession, there likely will not have been enough time between the disasters for the communities to rebuild. This phenomena could result in a greater number of deaths when experiencing subsequent disasters because people did not have adequate shelter. Most importantly, for this chapter I wish to measure adaptive capacity as it relates to the ability of communities to "build back better". If I cannot ensure that the communities I am observing aren't first re-built, there will be no way to accurately measure this variable. To account for locations that experienced multiple disasters in rapid succession, I narrow my definition of what it means to have previously experienced a disaster to only places that experienced another disaster five or more years ago. I chose five years because when looking at the average number of deaths per year experiencing a previous disaster, I find that at around five years after the disaster the average number of deaths begins to fall, suggesting that communities have been rebuilt. Because I am interested in comparing communities that did not experience a previous disaster to those which experienced a disaster aat least five years ago, I filter out the disasters that had previous disasters that were within the preceding five years.
<!-- [NOTE: I am currently finishing cleaning the chapter 2 rebuilding data. When I have that I will likely change 5-years to the average rebuilding time] -->


# Results

## Adaptive Capacity
### Broad Definition of State Capacity

\input{Ch3_Exhibits/dif_cap.tex}

Table 1 shows the results for the three models exploring adaptive capacity as measured by differences in log deaths, deadliness, and total deaths. Interestingly, there are no significant results indicating the direction or size of the relationship between state capacity and adaptive capacity. The model using changes in log deaths to measure adaptive capacity, while not significant, finds an association between greater state capacity and greater deaths while the other two models find negative relationships. The only two statistically significant results shown in the table include a positive --- albeit quite small --- relationship between GDP and change in total deaths and a negative relationship between the squared time since the previous disaster and log deaths. Interestingly, across all three models, there are negative relationships between squared time since the previous disaster and deaths, suggesting that as time passes, adaptive capacity increases. This relationship could be driven by a number of factors including technological advancement, disaster-related adaptation, or a reduction in the strength of subsequent disasters. To fully understand this relationship, more research is needed.

### State Capacity Components

\input{Ch3_Exhibits/dif_cap_comp.tex}

Table 2 shows the results for the three models observing the relationship between the adaptive capacity death differences and the three sub-components of state capacity. As with the Table 1, the results of this model are largely insignificant, meaning that the chosen data does not effectively explain the variation in adaptive capacity. Interestingly, there is a slightly negative relationship between adminstrative capacity and total deaths, meaning that an increase in administrative capacity is slightly associated with a decrease in decrease in deaths in a subsequent disaster. The large insignificance of these results could exist for a number of reasons including the omission of the disaster magnitude variable, or potentially because the included covariates simply cannot explain the variation in adaptive capacity. Future scholars should consider more detailed case studies to better understand the rebuilding process and the role of the state in that process.
<!-- look into filtering for only the first two disasters -->

## Basic Robustness Test

This following section explores adaptive capacity not in terms of differences between two specific events in a given location, but instead, observes variation in log deaths, total deaths, and deadliness amongst locations that have previously experienced disasters and those that have not

### Broad Definition of State Capacity

\input{Ch3_Exhibits/simple_adapt.tex}

Table 3 shows the regression output from the basic test explained above. Interestingly, as seen in Chapter 1, this table shows that increased state capacity is significantly associated with a decrease in both the deadliness of a disaster and disaster-related deaths. While these results are statistically significant, they may not be practically significant. A 0.04 decrease in the ratio between the number of deaths and the number of people affected by a disaster is quite small and while all lives are important, a 1.2 decrease in total deaths attributed to a one-unit increase in state capacity is not meaningful. 
The effect of experiencing a subsequent disaster is negative for both the deadliness measure and the total number of deaths but not statistically significant for either of them. Interestingly, despite state capacity and experiencing a subsequent disaster both having negative relationships on the outcome variables when observed alone, the interaction effect in which the simultaneous relationship between the two variable and the outcome variables was positive, meaning that when viewed together, state capacity and experiencing a subsequent variable are associated with increased deadliness and total deaths. This relationship is not statistically significant for either outcome variable meaning that it should be looked at with a healthy skepticism.

### State Capacity Components

\input{Ch3_Exhibits/components_adapt.tex}

Table 4 shows the regression output of the full-data model in which the three main components of state capacity: administrative capacity, coercive capacity, and extractive capacity are observed separately from one another and in relation to state capacity. Table 4 shows that the interaction effect between administrative capacity and experiencing a subsequent disaster is negatively associated with both deadliness and total deaths. These relationships are not statistically significant --- unlike the relationship between administrative capacity alone and the outcome variables --- suggesting that there may not me a meaningful interaction between these two variables. This interaction insignificance could also be attributed to the insignificance of the relationship between experiencing a subsequent disaster and the two outcome variables. The story of coercive capacity is  similar to that of administrative capacity, with significant negative relationships between coercive capacity alone and the outcome variables but statistically insignificant interaction effects. Interestingly, in this case, there is a positive relationship between the interaction effect between coercive capacity and experiencing a subsequent disaster and deadliness, but a positive relationship between the interaction effect and the total deaths outcome variable. While seemingly contradictory, these outcomes can logically exist simultaneously. Because "deadliness" is calculated by dividing the total number of deaths by the total number of affected people, an increase does not necessarily mean that fewer people died, but that fewer people died relative to the number of people affected. Finally, the interaction effects between extractive capacity and experiencing subsequent disasters and the outcome variables are all positive, but again, insignificant.







<!-- ## Adaptive Capacity - Chapter 3 -->

<!-- To measure adaptive capacity, I solely rely on the EM-DAT dataset. The EM-DAT data includes information on the type of disaster, the severity of the disaster, how many deaths were caused by the disaster, and the total economic damages. Because EM-DAT spans such a long time-period, I am able to filter for communities that experience the same type of disaster with the same severity multiple times. I then am able to use the deaths and economic damages^[I am less convinced that economic damages is a good way to measure this because with greater economic growth also brings greater potential losses due to disasters. In other words, if there is no infrastructure to be destroyed, the economic losses from a disaster would be zero.] data to compare how the same community fared in the aftermath of the original disaster. A nation that demonstrates significant adaptive capacity would see fewer deaths and losses the next time they experience a similar disaster, showing that they learned from the initial disaster and rebuilt in a way that greater protected them from similar disasters. -->

