---
geometry: "left=2in,right=1in,top=1in,bottom=1in"
output:
  pdf_document:
        latex_engine: xelatex
        toc: true
        toc_depth: 3
        extra_dependencies: float
        number_sections: true
mainfont: Times New Roman
# link_citations: yes
header-includes: \usepackage{setspace}\doublespacing\setlength{\parindent}{4em}\setlength{\parskip}{0em}
# fontsize: 12pt
# mainfont: Arial


bibliography: references.bib
---

```{r setup, include=FALSE}


# The below code creates a bibliography and allows for the tables and figures to
# be placed where I want them to be

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")
knitr::write_bib(c("base", "tinytex", "knitr", "kableExtra", "latexpdf", "readtext", "utils", "stargazer", "tidyverse", "sandwich", "lfe", "grid", "RColorBrewer", "rgdal", "rgeos", "maptools", "seg", "splancs", "gridExtra"), "bibliography.bib", width = 60)

# load r packages

library(tinytex)
library(knitr)
library(kableExtra)
library(latexpdf)
library(readtext)
library(utils)
library(bookdown)

library(janitor)
library(tidyverse)
#
# # need to load latex package "dcolumn" to allow latex tables to run and package
# # "float" to place tables and figures where I want them to go
#
usepackage_latex("dcolumn")
usepackage_latex("float")

```

\newpage

# Introduction

In a world where natural hazards are becoming increasingly frequent, how nations prepare for and respond to these hazards can determine whether these hazards result in disasters. Although related, natural hazards and natural disasters are not the same. Natural hazards are geological or weather events that have the potential to cause damage, while natural disasters are the negative impacts and harms caused by the natural disaster. While natural hazards do not discriminate on the basis of nationality, natural disasters do. In 1971 Chile experienced a magnitude 8^[Earthquakes are measured on the Richter Scale which is an exponential measurement of both the magnitude and scope of an earthquake. While there is no maximum on the scale, a magnitude 8 earthquake is extremely severe and there have only been a handful of earthquakes that register above the 8 range.] earthquake killing 85 people and affecting over 2 million people [@emdat]. Eight years later, over 2000 miles north of Chile, Colombia also experienced a magnitude 8 earthquake but with much more disastrous consequences. While the Colombian earthquake affected fewer people (11 thousand versus 2 million), it killed 579 people, nearly seven times more than were killed eight years before by the Chilean earthquake of the same magnitude. The differences between the outcomes of these countries become even more apparent when looking at the ratio of the number of people killed to the number of people affected - this statistic shows that the magnitude 8 earthquake Colombia (ratio: 0.05) was 1667 times more deadly than Chile's (ratio: 0.00003) earthquake. 

What accounts for these differences in outcomes for places experiencing the same hazard with the same magnitude? One commonly cited answer is money --- richer countries are better able to prepare for and respond to disasters [@zorn2018natural]. With larger incomes come better living conditions, citizens can afford more structurally sound homes and can invest in both insurance and preventative design. While income oftentimes can can explain this variation in outcomes^[One example of the role that money can play in disaster-related outcomes comes from South Asia. In late 2017, India and Sri Lanka were both impacted by a tropical cyclone with 130 kilometer per hour winds [@emdat]. While this was a single natural hazard that hit each country with similar force, the outcomes of these disasters were not the same: In India this cyclone resulted in 884 deaths while in Sri Lanka there were only 27 [@emdat]. This disparity in outcomes becomes even more apparent when considering the non-deadly impacts of these disasters - in India, 60,000 people were impacted by this event while in Sri Lanka that number was nearly triple that with 160,077 people being affected. This means that the ratio of deaths to affected people was 87.5 times greater in India than it was in Sri Lanka. In 2017, Sri Lanka's GDP per-capita (\$4,076) was just over two times that of India (\$1,980).] among similar hazards, it does not explain this variation. Chile and Colombia had very similar GDP per-capita values at the time of their earthquakes, \$1,094 and $1,061 respectively [@emdat].^[Both values are calculated using the value of the 2021 dollar and are thus comparable.] If GDP per-capita can't fully explain this variation in disaster-outcomes then what can? One potential explanation for these differences in outcomes is state capacity or a nation's ability to govern and implement policies [@besley2010state]. According to one measure by @hanson2021leviathan, at the time of their respective earthquakes, Chile's state capacity was significantly greater than that of Chile, ^[The @hanson2021leviathan state capacity is infinitely bound but most values fall between -3 and 3. In 1971 Chile registered a 0.87 on the scale while Colombia registered a -0.0022 in 1979.] suggesting that this variation in disaster outcomes may be able to be attributed to state capacity. This thesis explores the role of state capacity in post-disaster outcomes, ultimately answering the question: What role does state capacity play in how nations fare with and recover from natural disasters?

## Why study disasters?

The last twenty years have seen a significant rise in the number of climate-related disasters, putting much of the world’s population, in particular those living in poorer nations and communities at increased risk [@ipcc]. According to the Centre for Research on the Epidemiology of Disasters, between 2000 and 2021, there were on average 415 natural disasters annually across the world. These disasters on average impact 198,627,757 people, kill 63,321 people, and cause over $141 million dollars in damage [@emdat].^[Dollar amounts are based off of 2021.] With Earth’s temperature continuing to rise further and with that the, frequency and severity of catastrophic weather events, the question of what enables nations to be prepare for and respond effectively in the face of these exogenous disaster shocks is more important than ever. Disaster risk reduction is a priority of both governments and the international community. At the 2015 UN World Conference on Disaster Risk Reduction in Sendai, Japan, the Sendai Framework, a series of disaster-related goals was adopted. The Sendai Framework consists of four main targets: 1. understanding disaster risk; 2. strengthening disaster risk governance to manage disaster risk; 3. investing in disaster reduction for resilience; and 4. enhancing disaster preparedness for effective response - "building back better" [@sendai]. This thesis contributes towards the international goals outlined in the Sendai Framework. As demonstrated by the sheer number of people affected by and killed by natural disasters and the likely increase in disasters caused by climate change, studying disasters is more important than ever.

## State Capacity and Disasters

Existing literature on the relationship between state capacity and disaster outcomes fails to deploy measures that meet concept, using variables including log GDP per capita and taxation as a percentage of GDP as proxies for state capacity. While interesting, these variables do not accurately represent state capacity and should not be operationalized as such. In this thesis I capitalize on recent developments in political science, taking advantage of new aggregate and disaggregated state capacity variables developed by @hanson2021leviathan, allowing me to accurately measure state capacity and its three components  --- administrative capacity, coercive capacity, and extractive capacity. These new independent variables enable me to more accurately understand the relationship between state capacity and disaster outcomes but also to break down the concept of state capacity to better understand the mechanisms driving the relationship. This approach allows for greater ease of interpretation and provides more targeted results, meaning that national governments may be better able to implement changes in response.

This thesis also innovates on the existing scope and measurement of disaster outcomes. Departing from the current literature, in addition to studying disaster outcomes immediately following a disaster, known as vulnerability, this thesis explores longer term outcomes: Resilience, or how long it takes to rebuild a community after a disaster; and for communities experiencing multiple of the same disasters --- Adaptive capacity, the difference between the number of deaths in prior and subsequent natural disasters. For measuring disaster vulnerability and adaptive capacity, I prioritize the use of count data and deadliness, a new measure that contextualizes deaths within the greater scope of the affected population. These new measures provide greater insight into the suffering of real people and are not abstract like log deaths. While all measuring death, total deaths, log deaths, and deadliness each capture an important aspect of the destruction. Gross or total deaths provide a straightforward indication of the death and destruction that can be attributed to the disaster. Models measuring total deaths output a coefficient representing the number of lives either saved or lost as a result of a one unit increase in state capacity. While very similar, log deaths are easier to model linearly and while more difficult to interpret, these models may allow for greater understanding of the relationship between the independent variables and disaster outcomes and the significance of this relationship. Finally, deadliness provides context for the relative destruction of the disaster. While deaths are important to measure, the deadliness variable provides an additional control for the population of the affected area. By contextualizing deaths within the affected area, I am able to distinguish between events that cause a lot of deaths due to there being a large affected population and those areas that may have fewer deaths as a result of having smaller populations.

<!-- This thesis seeks to explore the relationship between state capacity and disaster-related outcomes. Because of the complex nature of this dependent variable --- disaster outcomes --- I focus on three separate disaster-related outcomes in this thesis: 1. immediate-term disaster related deaths, 2. the length of time it takes to rebuild a community after a disaster, and 3. for communities experiencing multiple of the same disasters --- the difference between the number of deaths in prior and subsequent natural disasters.  -->

While more commonly defined by its absence, state capacity can be simply defined as a state's ability to implement its goals or policies [@cingolani2013state]. If a government can control its territory, it will be easier to coordinate a response, bring in outside help, and to rebuild without fear or the risk of additional destruction by violent non-state actors. Because state capacity is such a broad concept, it can be difficult to directly address the mechanisms behind its relationships with different outcome variables. @hanson2021leviathan and @mao2021 address this dilemma, breaking down the concept of state capacity into three components: administrative capacity, coercive capacity, and extractive capacity.^[@hanson2018state also similarly breaks down state capacity into three components, slightly different than from listed above: bureaucratic/administrative capacity, military capacity, and the quality of a nation’s political institutions.] 

These three components translate directly to three of the mechanisms driving the relationship between disaster outcomes and state capacity. Administrative capacity, or the strength and reliability of a nation's bureaucracy determines whether national action is taken both before and after a disaster. Strong building regulations and regulation enforcement fall under administrative capacity along with government infrastructure pertaining to early disaster warning systems. After a disaster, relief and reconstruction efforts must be ordered and coordinated and new technology adopted to prevent future destruction. How much administrative capacity a country has determines whether, and how well these efforts are made. Coercive capacity, or a nation's ability to compel its citizens to act in a given way also has both pre and post disaster effects. Before a disaster, a nation's coercive capacity determines whether citizens comply with existing regulations. For instance, there could be a law prohibiting the construction of new homes in a flood plane, but unless there is sufficient coercive capacity, people may choose to ignore the law and build there anyways. After a disaster, coercive capacity can influence whether the rule of law remains among the destruction, a necessary precondition for effective rebuilding. Finally, the most nebulous of the three, extractive capacity is a nation's ability to extract revenue from its population. Extractive capacity can dictate a country's tax and overall revenue base, providing the government with the funds to effectively implement disaster prevention infrastructure and relief funding. Extractive capacity that is derived from taxation indicates trust in the central government - greater trust may indicate greater capacity.

In this thesis, I hypothesize that increased state capacity will be associated with better disaster outcomes: fewer deaths, less deadliness, and a shorter rebuilding process. 

ADD HERE MORE SELLING OF RESULTS

The results of my analysis are mixed. While I do find that increased state capacity is associated with fewer deaths and less deadliness in the immediate term, the results for rebuilding time and the effects of having more than one disaster are unclear. The following section provides an overview of the objectives and findings of each chapter.

## Thesis Chapter Outline

Chapter 2 provides an overview of existing state capacity and disaster literature. Through this overview, I identify key components of both independent and dependent variables, arguing that current work fails to accurately measure the complexity of both state capacity and disaster outcomes. In this chapter, I identify State capacity, the main independent variable consists of three sub-categories: administrative capacity, coercive capacity, and extracitve capacity. Chapter 2 breaks down disaster outcome into three temporal components: 1. immediate-term deaths or how many people die as a result of the disaster; 2. how long it takes for communities to rebuild; and 3. how having previously experienced a disaster impacts deaths when impacted by a subsequent disaster. In this chapter, I hypothesize that greater state capacity will result in less initial destruction, shorter rebuilding times, and fewer deaths when experiencing a subsequent disaster.

Through employing new measures of state capacity and its components, Chapter 3 builds on the existing short-term disaster vulnerability literature. Beginning with
a robustness check on the this literature, I test whether the findings remain true when measuring total deaths and deadliness in addition to log deaths. My findings are consistent with @lin_governing_2015, @kahn2005death, and @tol2021state, finding that both greater GDP per capita and greater tax revenue as a percentage of GDP are associated with fewer disaster-related deaths. With this complete, I then use linear regression to observe the relationship between state capacity, its components, and three immediate-term outcome variables: total deaths, log deaths, and deadliness or the ratio of deaths to the number of people affected by the disaster. Interestingly, I find that all three outcome variables significantly decrease when aggregate state capacity and administrative capacity increase. The results are less clear for coercive and extractive capacity, suggesting that administrative capacity is driving the relationship between aggregate state capacity and vulnerability.

Looking beyond the immediate effects of disasters, Chapter 4 focuses on the medium-term or rebuilding process. Because obvious measures for rebuilding duration and project satisfaction are not readily available, I use foreign aid projects devoted to disaster reconstruction as a proxies for the greater rebuilding process. The AidData dataset includes information both on project duration how satisfied donors are with their projects. Observing the relationship between state capacity and project length, I find evidence of a positive, albeit only slightly significant relationship between state capacity and project duration, meaning that increased state capacity is associated with longer rebuilding times. Importantly, when observing project duration in its log form, I find a significant negative relationship between state capacity and project duration, suggesting that maybe the count model used does not account for all of the variation in the data. When observing the three components of state capacity, I find a significant negative relationship between both administrative capacity and coercive capacity and log project length, suggesting that these two components are driving the relationship between the broad state capacity measure and log project length. 

The final empirical chapter, Chapter 5, analyzes the long-term outcomes of locations experiencing two or more of the same disaster, exploring the concept of adaptive capacity, or whether prior exposure to a disaster enables communities to fare better when hit again. Like in Chapter 3, I measure total deaths, log deaths, and deadliness, but this time, I compare these values with those from previous disasters in the same location. The difference in these outcomes between prior and subsequent disasters is my variable of interest. In my analysis of the relationship between state capacity and these difference variables I do not find significant results for this relationship but I do find that greater time between disasters is significantly associated with fewer log disaster deaths. As a robustness check I run the same models as in Chapter 3 with an additional control variable indicating whether the disaster being measured is a subsequent disaster. I similarly do not find a significant relationship between state capacity, whether a location is experiencing a subsequent disaster and the number of deaths.

Chapter 6 concludes this thesis by synthesizing my findings, emphasizing the important role that state capacity plays in disaster outcomes and the importance of using precise and targeted measures for both state capacity and disaster outcomes.

\newpage


# Overview of Disaster Literature

To understand the relationship between state capacity and disaster outcomes, we must first understand the context within which these questions arise. 

While natural hazards and the disasters associated with them are largely singular events, the aftermaths are not. Through synthesizing theory from both the social and physical sciences, @gallopin2006linkages addresses this phenomenon, providing a framework with which to observe reactions to socio-ecological events. @gallopin2006linkages breaks the aftermath of a disaster into three components: vulnerability, resilience, and adaptive capacity. Vulnerability refers to how a nation fares shortly after being struck by a disaster and depends on two key categories: exposure to the disaster and sensitivity to disasters. How exposed a community is to a disaster is determined by the strength and scope of the disaster [@adger2006vulnerability; @kasperson2005vulnerable], while sensitivity indicates how affected or changed the community is as a result of the disaster [@gallopin2003box]. Similar to how certain age or genetic traits can affect how sensitive a person is to particular diseases, some nations or communities are more sensitive to natural disasters. Resilience, the second component of  disaster response mentioned by @gallopin2006linkages represents the ability of a community to cope with a disaster and respond positively, in other words, whether a community is able to rebuild effectively. The third component identified by @gallopin2006linkages is adaptive capacity, defined as a community's ability to not only be resilient, but to improve its condition in the face of a future similar threat. While resilience largely relates to a community "getting back on their feet" and recreating what was lost, adaptive capacity includes that, but goes a step further and includes the idea of "building back better" so that future hazards do not have the same disastrous affects on the community as before.

These three components of disaster response map neatly onto the temporal aspect of natural disaster responses: the immediate, medium, and long terms. Vulnerability largely plays a role both during and in the immediate aftermath of the disaster, resilience determines the rebuilding process or medium-term aspect of disaster response, and adaptive capacity determines the long-term outcomes of the community if another similar disaster is to hit the community or nation.

Much scholarly work exists on the relationship between natural disaster outcomes and state capacity, but the majority of research focuses on short-term vulnerability to natural disasters [@kahn2005death; @lin_governing_2015; @tol2021state], or on individual and private sector responses to disasters [@sawada2007impact; @drabo2015natural; @sawada2017natural; @rivera2014social], neglecting the roles that centralized states can play in disaster responses. While research on the longer-term aspects of disaster response do exist, the focus has been largely on post-mortem assessments of disasters striking developed nations [@dacy1969economies, @peacock2000hurricane, @aldrich2015physical, @wright1979after, @rossi1993community], or on the extremely long-term concept of post-disaster creative destruction which fails to consider the concept of adaptive capacity [@skidmore2002natural].

Post-disaster resilience and adaptive capacity, measuring medium and long-term disaster outcomes, are under-theorized areas of political science, indicating a critically important gap in the literature. While salient and topical, the lack of medium to long-term literature, especially pertaining to the developing world becomes understandable when considering lack of available data and the difficulty of gaining such data. To measure the recovery process, one must be able to measure a multitude of variables including the rebuilding of homes, infrastructure, businesses, etc. This is difficult in the best of circumstances but situations with limited record-keeping and government oversight make measuring resilience even more so. Measuring adaptive capacity requires researchers to compare two similar events happening to the same nation after rebuilding. This narrow scope of observation makes for a smaller potential sample size in addition to other challenges.

Unlike resilience and adaptive capacity, the relationship between short-term vulnerability and state capacity has been explored, but explored imperfectly. 


Exploring the relationship between log GDP per capita and disaster related deaths, @kahn2005death and @lin_governing_2015 argue that greater state capacity is associated with reduced disaster mortality among affected people.  @tol2021state builds on this work, arguing again that greater state capacity leads to less vulnerability to disasters, but unlike @lin_governing_2015 and @kahn2005death, instead of using log GDP per capita to represent state capacity, @tol2021state takes a more sophisticated approach, using taxation and the size of the national bureaucracy as proxies for state capacity. According to @tol2021state, nations with greater tax revenue suffer both fewer disaster-related deaths and have fewer people affected by disasters when they do strike. While claiming to represent the relationship between state capacity and disaster related deaths, all three of these papers fail to propose measures that meet concept: while they may be related, log GDP per capita, taxation as a percentage of GDP, and the size of national bureaucracies, while interesting measures, should not be considered as perfectly representing state capacity.

While the strength of a nation's economy can sometimes indicate state capacity, this relationship does not always hold true, and using log GDP per capita as a proxy for state capacity ignores the important literature on this topic. While @besley2010state describes a symbiotic relationship between strong states and strong economies, this relationship only holds true when the economy is tied to the welfare of the people. Countries in which governments depend on citizens for resources have incentives to help grow the economy so that they can extract more [@sanchez2020origins] --- this is a win-win situation in which the economy grows, and both the state and the people profit from this growth. This inclusive economic growth can be contrasted with countries experiencing a textbook "resource curse". In nations with vast natural resource stores, the economy is not necessarily tied to the welfare of the people, meaning that the state can gain resources and capacity without community benefit or buy-in [@ross1999political; @mehlum2006institutions; @sanchez2020origins]. @sanchez2020origins provides examples of both of these phenomena in the context of the Democratic Republic of the Congo through contrasting communities with two different resources: gold and coltan^[Coltan is a mineral used in many electronic devices.]. Because gold is mined in small, easily concealable nuggets, communities with large gold stores had a comparatively higher state presence. In order for the government, in this case armed bandits, to generate revenue from the area, they had to create a system of taxation because mining all of the gold would not be possible. @sanchez2020origins contrasts these communities with those in which large stores of coltan exist. Because this coltan cannot be acquired by regular people and requires specialized equipment to mine, to generate income from the resource, the government needs only to protect the resource and ensure that it is exported. Communities with large coltan mines unlike those with gold did not have present taxation systems, had lower state capacity, and increased levels of violence. @sanchez2020origins demonstrates the limitations of solely relying on the economy as a representation of a nation, or in the case of the paper, a local government's strength.

While still insufficient, @tol2021state's taxation as a proportion of GDP and the size of a nation's bureaucracy are more precise indicators of state capacity than log GDP per capita. For governments to effectively extract resources from citizens through taxation there must be a reasonable state infrastructure set up. A greater proportion of GDP coming from taxation suggests that a nation relies on the economic activities of its citizens to generate revenue rather than natural resources seperate from the population. Taxation also represents a social contract between citizens and their leaders, suggesting that the government has an obligation to act in the best interest of the people. While the relationship between taxation and state capacity is convincing, taxation is not state capacity and should not be operationalized as such. Similarly, the size of a nation's bureaucracy could suggest a strong government capable of carrying out policies, or, instead, a bloated and corrupt bureaucracy unable to perform its duties.

Having identified the shortcomings of the current literature both in terms of the time periods considered and the variables used to measure state capacity, the remainder of this chapter explores more comprehensive measures for state capacity and the mechanisms driving their relationship with all three stages of disaster outcomes.

<!-- @garnett2010enhancing provides an overview of different disaster responses in the developing world, finding through an assessment of numerous case studies that strategies focusing on local empowerment, organization and leadership, sustainable planning, and a free-market economy ultimately have more positive outcomes for affected communities. To understand the role state capacity and finer-grained components of state capacity have on disaster response it is important to understand the basis of state capacity.  -->

## Operationalizing State Capacity

Most simply defined as a state's ability to implement its goals or policies [@cingolani2013state], as evidenced by the failure of the existing disaster literature to accurately measure it, state capacity is rather difficult to measure. @hanson2021leviathan, @mao2021, and @hendrix2010^[@hendrix2010 breaks down the concept of state capacity slightly differently than the others into military capacity, bureaucratic/administrative capacity, and the quality of a nation’s political institutions.] all address this ambiguity by breaking down state capacity into three components: administrative capacity, coercive capacity, and extractive capacity. Administrative capacity pertains to a nation's ability to carry out necessary tasks, the ability to create policies and implement them [@hanson2021leviathan]. While similar to @tol2021state's size of the national bureaucracy, administrative capacity prioritizes competence over size, meaning that the measure more accurately reflects the governance ability of a nation rather than simply the number of people in its employ. Coercive capacity indicates a nation's ability to "dominate society" or to engender compliance among citizens. Coercive capacity relies both on the strength and size of the nation's military but also the maintenance of law and order domestically [@hanson2021leviathan]. Finally, extractive capacity pertains to a government's ability to raise revenues from its territories and to use them to govern. While @tol2021state accounts for this variable, it is important to note that extractive capacity is just one component of state capacity and should not be used as a comprehensive indicator. The following sections explore the underlying mechanisms impacting these different aspects of state capacity.


<!-- In the context of natural disaster resilience and adaptive capacity, how quickly and effectively a community is able to be rebuilt is incredibly important. The longer it takes for homes and businesses to be rebuilt, the longer people are displaced and the economy stagnated. Like state capacity more broadly, bureaucratic efficiency relies upon the effective functioning of the government, but instead of ability, it focuses on how quickly governments can execute necessary functions ( @prendergast2003limits), in this case, how quickly a disaster response can be initiated.  When a disaster strikes a community, there is an initial large disruption with people being displaced, infrastructure damaged, and overall panic. How quickly a community can begin rebuilding and ultimately recover from a disaster depends on how quickly systematic efforts are initiated to begin and carry out the recovery process. A more efficient bureaucracy allows for less “red tape” that can make rebuilding difficult and lengthy. @garnett2010enhancing in its assessment of states that responded effectively to natural disasters found that the decentralization of disaster response agencies allowed for more efficient responses and faster action after a hurricane in Honduras. Issuing of a time-sensitive emergency mandate in Mexico after an earthquake resulted in faster rebuilding. Both of these events show that prioritizing swift action can facilitate faster rebuilding after a disaster. Additionally, the Sendai Framework for Disaster Risk Reduction, the UN's framework for effective disaster response, encourages the decentralization of post-disaster governance to encourage local empowerment/investment and a swifter response ( https://www.undrr.org/implementing-sendai-framework/what-sendai-framework).  -->

### Administrative Capacity

The link between administrative capacity and disaster outcomes can best be understood through the lens of accountability. For governments to demonstrate high administrative capacity in the face of a natural disaster, they must have both the willingness and ability to act competently. This willingness to respond effectively and efficiently can be partly driven by citizens holding thier governments accountable. To understand this relationship I use the principal-agent relationship as a model. In this framework there are two groups: the principals who are the main entity, and the agents who are tasked with making decisions in the best interest of the principals [@eisenhardt1989agency]. In a democracy, elected officials are the agents of the people, meaning that the citizens, or principals entrust them with acting in their best interest [@garen1994executive] and in order to remain as agents, elected officials must be re-elected. This principal-agent relationship may be the missing piece in the puzzle of state capacity and disaster response. @back2008democracy argue the existence of a j-shaped relationship between democracy and state capacity, claiming that while a robust democracy has the most state capacity, authoritarian states have more than emerging democracies due to the strength of their bureaucracies or administrative capacity. Both authoritarian states and robust democracies are able to have strong administrative capacity, but they differ in where they derive their power. Authoritarian states have a top-down structure governed by control and fear while strong democracies gain their power from public accountability, cooperation, and transparency --- the principal-agent relationship. @lin_governing_2015 finds evidence of a negative relationship between democracy and disaster mortality rates, suggesting that democratic regimes are better able to respond to and prepare for natural disasters. Interestingly, @lin_governing_2015 finds that voters typically prefer relief spending over spending on prevention, suggesting that the mechanism behind the relationship between democracy and disaster resilience is not due to political pressure to prepare for disasters but instead can potentially be attributed to the government's relationship with and obligation to its citizens in the aftermath of the disaster.

<!-- Both are effective at promoting administrative capacity because they have the ability to control people – one through community buy-in and the other through fear/the ability to punish. This relationship has implications for disaster recovery and response.  -->

Information asymmetry and clientelism are seemingly the largest forces that can pervert accountability and lessen administrative capacity.  Information asymmetry happens when the principals do not have access to all necessary information to effectively hold agents accountable, thus distorting the relationship and leading to sub-optimal outcomes for principals and the community at large [@waterman1998principal]. Clientelism or vote buying is another way in which this relationship can be distorted --- when votes are bought, the principals have an added variable in how they assess and hold accountable their agents [@keefer2008democracy]. Much literature suggests that when voters have information about politician preferences and performance [@platas2019closing, @carlson2015ethnic] they are better able to vote for politicians that align with their beliefs.  Similarly, when given information about corruption or about the role of government, citizens --- and in some cases government officials --- are able to hold officials accountable through voting them out of office [@ferraz2008exposing, @gottlieb2016greater, @blattman2019eat], and in the case of politicians controlling bureaucrats, increased oversight of budgets can reduce corruption [@raffler2016does].  Accountability also is impacted by clientelism, with vote buying in many cases perverting the principle-agent relationship so that politicians use citizens as agents to promote them to power [@stokes2005perverse]. Regimes with robust democracies in which politicians are held accountable for their actions can be expected to have greater administrative capacity and facilitate more efficient recovery processes. @cooperman2021natural provides evidence of this accountability link, finding that in years when politicians are up for re-election they are more likely to declare a state of emergency to allow funds to be sent in to facilitate the recovery process.

<!-- Unlike the work mentioned above in which citizens (principals) hold their politicians and governments (agents)  accountable through elections, in the case of disaster response, the time-line is much shorter, at least in the beginning, meaning that it is important to observe accountability not as an outcome in an experiment but as something embedded in the community. In addition to understanding how voters and people hold elected officials accountable, it is important to also understand how local people can feel empowered to support public works projects in their communities. In the economic development field, there is strong evidence that when community members are asked for and provide input on potential aid projects that projects focus more on the wishes of everyday people rather than political elites, leading to overall greater satisfaction with the project [@olken2010direct, @beath2017direct, @beath2018can]. Evidence from Findings from @garnett2010enhancing support this argument. In their analysis of a number of catastrophic environmental events, they found that initiatives that directly involved citizens in rebuilding after a disaster were more successful and efficient. For example, in the aftermath of a 1998 flood in Bangladesh, the country’s free market allowed for grain to quickly be imported from abroad and was much faster than the government’s grain assistance. While not necessarily democratic accountability, the democratization of disaster response allows citizens to see a need and work together to meet it. -->

### Coercive Capacity

The most basic indicator of state capacity, coercive capacity is a necessary precursor for the existence of a state. The existence of a military can be one of the earliest indicators of the formation of a state, with @tilly1992coercion famously arguing that states arise because of a social contract between the governed and the governing --- governments will protect the people from outside threats in return for payments in the form of taxes. Similarly, historical warfare is believed to serve as a predictor of modern-day state capacity, with states gaining capacity as they capacity forced to raise more taxes from their people to fight wars [@north1989constitutions]. Importantly, this military view of state capacity is not universally applicable. While true for Europe and Asia, in the African context, this increased state capacity due to wars often manifests itself in the creation of special-interest states: states with both high fiscal capacity and levels of civil-conflict [@dincecco2019africa]. These special-interest states with strong militaries are ripe grounds for warlords which use their coercive capacity not to protect citizens from outside threats but to stifle perceived internal threats and extract resources from the people [@robinson2002states]. While important, military strength on its own does not fully explain coercive capacity.

Similar to the strength of a nation's military, the existence, strength, and legitimacy of local law enforcement also impacts a state's coercive capacity. The existence of law enforcement contributes to coercive capacity in two ways: through the employment of the institution to actually arrest and punish infractions but also through the threat of punishment [@hanson2021leviathan]. The existence of these forces and the knowledge that there are consequences for violating laws encourages compliance, thus increasing coercive capacity. Finally, coercive capacity's final component relates to the state's level of institutionalization, or how present the state apparatus is in a given territory [@hanson2021leviathan]. The more present the state is the greater the existence of both the military and law enforcement, thus, greater coercive capacity.

<!-- Both are effective at promoting administrative capacity because they have the ability to control people – one through community buy-in and the other through fear/the ability to punish. This relationship has implications for disaster recovery and response.  -->

<!-- Military capacity contributes to state capacity in three distinct ways: as an example of a public good, as an indicator of taxation abilities, and through its repressive capacity. Militaries are public goods, and when not used against their own citizens, investments in them are investments in the interest of all citizens [@besley2009origins].  -->


### Extractive Capacity

Finally, extractive capacity relies on both administrative and coervive capacity. To effectively extract resources from its population, a state must have the necessary administrative infrastructure to manage the taxation process and be able to compel its population to comply with these measures. A nation needs revenue to function and thus extractive capacity indicates a nation's ability to govern. While extractive capacity pertains to any form of revenue generation, this thesis focuses on extraction through capacity as it is a more comprehensive indicator, showing both a nation's revenue but also the willingness of the people to contribute to the state. As explained earlier, the ability of a nation to generate revenue through taxation is largely dependent on the size of the economy, in particular, the size of the economy that relies on the economic activities of everyday people, how inclusive economic institutions are [@sanchez2020origins].

Inclusive institutions are economic and political systems which allow people to freely participate and benefit from the fruits of their labors [@acemoglu2012nations], they include legal systems that protect property and intellectual property rights and important bureaucratic jobs in both the public and private sectors that are merit-based. Nations with inclusive institutions are characterized by sufficient state capacity [@fukuyama2012future] but also by opportunities for citizens to participate in both the economy and politics in the ways that they deem best fit [@acemouglu2016paths]. With inclusive institutions, there are fewer barriers to entry in markets, allowing an entrepreneur to see a need, enter a market, and potentially profit from their idea. Inclusive institutions allow for the free market to operate at its most optimal level, enabling people with talent and ideas to execute them regardless of previous privilege or position. Inclusive institutions allow for greater economic growth, thus increasing the state's extractive capacity.

<!-- While the actions of the government are important for how resilient a nation is to natural disasters, in order for actions to be carried out and efficiently, there  must be cooperation both between the government and the people (trust, accountability, democracy) and between people (social cohesion). Social capital and trust between the most vulnerable citizens and government officials is as important as the physical infrastructure rebuilding. When communities lack trust, they struggle to self organize and provide mutual aid to fellow citizens - this can result in less cooperation with relief and rebuilding projects ( @aldrich2015social). -->

<!-- Especially salient in the developing world, ethnicity plays an important role in national cooperation and in the sense of a common identity. The ability of a community to collectively act is largely determined by the number of people in the community, their ability to trust each other and work together, and in some circumstances, the heterogeneity of the community (part of the trust dynamic) (@ostrom2007collective).  Ethnicity plays a large role in community trust but it is not completely clear what the shape of the relationship is.  There is evidence that more diversity actually improves the odds of collective action ( @posner2004political, @robinson2014national), but simultaneously, it is believed that increased diversity makes it more difficult for people to cooperate and decreases collective action ( @ejdemyr2018segregation, @habyarimana2007does).  I suspect that there may be a u-shaped relationship between diversity and collective action where homogeneous and extremely heterogeneous communities will both have higher levels of social-cohesion and are able to effectively act collectively while communities with one or a few dominant ethnic groups struggle more.  -->

<!-- Ethnicity is just one factor that can influence social cohesion, religion and income also play a role in social cohesion. @kawachi1997social find that smaller differences in income between people result in people viewing their social environments as less hostile and more hospitable. Much literature exists on the role of a middle class in economic development ( @banerjee2007economic, @birdsall2000stuck, @easterly2001middle) and in strengthening democratic institutions ( @fukuyama2012future), suggesting that a robust middle class both increases state capacity and social cohesion. Regardless of the strength of the government response to a natural disaster, recovery and rebuilding still requires work by citizens. When citizens trust eachother and can cooperate more easily, inefficiencies are reduced and more time, energy, and resources can but put into the rebuilding process. -->

## A Theory of State Capacity and Disaster Response

As mentioned earlier, the existing literature falls short of explaining the relationship between state capacity and disaster outcomes in two main ways: through incorrectly operationalizing state capacity and through only focusing on vulnerability, or short term disaster outcomes. This thesis addresses both of these shortcomings. In this section I identify the key dependent variables I will measure and generate hypotheses that will be tested in the following three chapters.

### Vulnerability --- Short Term Outcome

Existing literature on the topic of natural disaster vulnerability and state capacity falls short due to the use of insufficient and limited variables to represent state capacity. This thesis departs from that practice, leveraging a recent and more comprehensive measure of state capacity developed by @hanson2021leviathan. Through the use 21 different indicators and Bayesian Markov-Chain Monte Carlo models, @hanson2021leviathan creates a comprehensive aggregate measure of state capacity. Unlike other measures used by @lin_governing_2015, @kahn2005death, and @tol2021state, the @hanson2021leviathan incorporates measures for all three state capacity components into this indicator and accounts for their interrelationship. Through the use of this comprehensive aggregate measure and stand alone indicators for administrative capacity, coercive capacity, and extractive capacity, I will expand the literature, testing the relationship between both state capacity and individual state capacity components and disaster related deaths. 

In addition to improved state capacity measures, I also expand the literature through the addition of two new dependent variable or death measurements. @lin_governing_2015, @kahn2005death, and @tol2021state all use log deaths as their dependent variable, a sensible choice for using a linear model but not one that returns easy to interpret results that inspire action. In addition to log deaths, this thesis also explores total deaths and the ratio of deaths to affected people, referred to as deadliness. These additional outcome variables allow for the real-life effects of state capacity on people's lives to be more easily interpreted. While a log death is difficult to conceptualize, total deaths and deadliness are not. 

Building off of the work of @lin_governing_2015, @tol2021state and @kahn2005death, I will test the relationship between state capacity and vulnerability using these new and improved variables. While I will use different measures, I expect greater state capacity to be associated with decreased vulnerability.

H1: *Greater state capacity as measured by @hanson2021leviathan will correspond with fewer disaster-related deaths and deadliness in the immediate aftermath the disaster.*

### Resilience --- Medium-Term Outcome

When rebuilding after the initial disaster, there are fewer things left to chance, meaning that there is more room for a capable state to take action and control how the situation is resolved. Even in situations in weaker or fragile states where much of the recovery is donor-driven, greater state capacity likely provides greater stability, support, and partnership to the aid organizations, helping them to be able to rebuild communities more quickly and efficiently. As defined by @gallopin2006linkages, resilience is a community's ability to cope with a disaster and respond positively, in short, whether a community is able to rebuild effectively. Effective rebuilding comprises of two components: 1) the speed of rebuilding, and 2) the quality of rebuilding. Ideally, a competent state will be able to facilitate a swift and quality rebuilding process. Incompetent states will result in people being displaced for longer than their more competent peers and with less satisfaction. Longer project durations and the mismanagement of resources can make the rebuilding process needlessly more expensive. The speed and quality of post-disaster rebuilding processes can be influenced by the following mechanisms:

#. The ability of the government to ensure stability in the disaster-affected area;

#. The ability of the government to assess damages from the disaster;

#. The ability to coordinate a response to the disaster, OR to work with an NGO/aid organization 

to coordinate a response.

Disaster preparedness is derived from "certain unintended consequences of state building" [@lin_governing_2015], meaning that a nation's institutions and infrastructure set the pre-conditions that determine how capable a state will be in coordinating a disaster response. Mechanism 1 explains this phenomenon. For a nation to effectively and efficiently rebuild, there must be stability within the affected area. I define stability as a state monopoly on legitimate violence [@weber1919], meaning that insurgents or armed actors are not vying for power or attempting to overthrow or replace the government. If a government can control its territory, it will be easier to coordinate a response, bring in outside help, and to rebuild without fear or the risk of additional destruction by violent non-state actors. Opponents of this idea may argue that in nations with particularly weak state capacity, insurgent actors may actually be better able to provide services and facilitate rebuilding than the actual government [@arjona2015rebel, @sanchez2020origins]. While these non-state actors are by the very essence of their name "non-state", they operate as one, and while their capacity is not state capacity, they can contribute to peace and stability, meaning that the monopoly on violence in the area does not necessarily have to be through the state. Stability can be ensured in a number of ways including the deployment of the military to assist citizens in need and through a relationship of trust between the citizens and their government. This trust is especially important. If the people affected by the disaster trust that assistance will be provided, they will be more likely to cooperate with the government or aid organization and less likely to attempt to overthrow the government, making for a swifter and more coordinated response. Without stability in the region, the higher-level disaster response and rebuilding coordination will be much more difficult, causing the process to take longer and ultimately cost more money.

Once stability is established, meaning that a response is able to take place, the next mechanism that determines how resilient a nation is is the ability of the government to assess the damages done by the disaster. To effectively respond to any negative event, in particular a large-scale natural disaster, it is important to know what damage has been experienced. In the case of natural disasters, this damage includes the number of lives lost, homes destroyed, food-producing farms decimated, and the precise locations of these losses. Knowing both the degree and location of these losses allows for targeted relief efforts directed to the areas that need the most assistance. While these seem like relatively simple metrics, to be able to quantify losses, state statistical capacity, or the maintenance of key records is of particular importance. Deaths and destruction may still be able to be counted without these records, but the process would likely be much more difficult and leave states partially blind to the initial conditions in their nations [@harsch2020]. Without key statistical information, it is difficult to identify areas hardest hit, thus slowing the disaster-response and recovery process.

The third mechanism behind disaster resilience is the ability of the state to either coordinate a response to the disaster, or in the case of a donor-driven response, to work effectively with an NGO/aid organization to facilitate the rebuilding process. Rebuilding post disaster requires intense coordination between national, state, and local governments, and between governments and people. In order to rebuild, the damage must be assessed, a chain of command must be established, rebuilding plans must be made, builders must be hired, funds must be administered to the necessary stakeholders, and materials must be purchased, all while citizens and stakeholders are kept appraised of what is going on. This response requires a high degree of state capacity, in particular administrative capacity.

Finally, while the ability of the state to enact post-disaster rebuilding programs and to effectively work with different aid organizations that are mobilized to help, without compliance and cooperation from the population, it is difficult for these policies to be enacted. The government's coercive capacity, or ability to compel compliance with policies in place is essential for enabling an swift and efficient rebuilding process. While state capacity can be an important predictor of short-term disaster outcomes, I expect the effect to be even larger in the longer/resilience-term. When a disaster strikes a community, a lot of the damage is inevitable - no amount of good policy can totally prevent the destruction created by an earthquake or a tsunami. With the rebuilding process though, there is a lot more room for policy, good or bad to impact the outcome - the longer the time horizon, the more opportunities there are for strong states to make positive decisions that affect resilience outcomes.

H2: *The greater a country's state capacity, the shorter the rebuilding time period will be*

H3: *The greater a country's state capacity, the greater the project satisfaction*

H4: *Administrative capacity has a stronger relationship with resilience than coercive or extractive capacity*

### Adaptive Capacity --- Long-Term Outcome

In addition to both the relationship between state capacity and short and medium-term outcomes, I am also interested in observing the relationship between state capacity and adaptive capacity. As defined earlier, adaptive capacity is the ability to "build back better" or to rebuild in a way that mitigates future risk to similar disasters [@gallopin2006linkages]. Quite similar to my theory of resilience, my theory of adaptive capacity relies on four mechanisms:

#. The ability to assess damages AND identify the weak points or vulnerabilities that enabled the destruction; 

#. The ability to finance the use of disaster-safe practices

#. Cooperation and buy-in from stakeholders 

#. The ability to migrate if one wishes to a safer area

Mechanism 1 highlights the importance of having sufficient assessment infrastructure in place to be able to take stock of the damage shortly after the disaster to find whether infrastructure changes could have mitigated some of the damage. A key component of adaptive capacity is learning through assessing past vulnerabilities how to build back in a way that will mitigate future risk. In addition to having sufficient statistical capacity as needed above to assess the damage, to know what vulnerabilities the past infrastructure had to disasters requires assessments by professionals. Initiating and authorizing these assessments requires an additional level of planning and foresight by the government but can provide important insight into what went wrong in the past. For a government to be able to initiate this kind of post-mortem assessment in the midst of the aftermath of a disaster requires a significant level of capacity and an emphasis on proactive planning in addition to reactive rebuilding. In particular, administrative capacity, or the ability to enact policies is especially important in ensuring that these actions are indeed taken and taken quickly.

Mechanism 2 may seem self-explanatory, but disaster-safe rebuilding practices can sometimes be expensive [@twigg2006technology], leaving governments and homeowners to decide between spending money they may not have on safer rebuilding practices or instead choosing to re-build homes just as they were before. Rebuilding homes in a more disaster-safe way may require additional aid, technological support, and education as to how and why these new ways of building can protect homeowners from future damage, all of which cost a significant amount of money.

In addition to the resources to rebuild in a disaster-safe manner, it is essential that there be community buy-in from the affected stakeholders. There may be a certain cultural significance tied to a certain way of building or stakeholders may not understand that by rebuilding a certain way that they may be safer when or if another disaster strikes. Even with the necessary technology and the finances to make it happen, if there is not community buy in, these changes will not be made. Mechanism 3 highlights the importance of a government's coercive capacity, or ability to convince citizens to act in a certain way. Educating local people both about how the technology works and how they themselves can use it will facilitate greater uptake and hopefully greater adaptive capacity.

Finally, and seemingly the most counter intuitive, a country's adaptive capacity, as measured by the number of deaths and displaced persons after the disaster is affected by the number of people who are in the community. In some situations in which climate change has resulted in certain communities permanently being at risk, the safest thing people can do is to leave and to move somewhere less susceptible. This comes with a number of cultural and ethical questions, but for the purposes of this study, I view people moving to safer areas a positive that will not only result in they themselves being at less risk, but will also result in fewer affected people when and if disaster strikes their original communities again.

Through assessing what went wrong in the past, engendering support for the new building measures among the affected population, acquiring significant resources, and allowing people to move away if they wish, communities can be rebuilt in a way that lessens potential future damage. 

H5: *The greater a country's state capacity, the greater their adaptive capacity*

\newpage

# Conclusion

With the prevalence and severity of extreme weather events expected to rise as a result of climate change and the Earth's rising temperature [@mcdaniel_weather_2021], the question of what enables nations to effectively respond to these events is becoming ever more crucial. While most nations alone cannot impact the factors that influence climate change, national-level decisions can impact how a nation responds and what level of destruction is experienced when a natural hazard occurs. Existing literature on the role of the state in natural disaster response largely focuses on disaster-related deaths in the immediate aftermath of a disaster and uses narrowly-scoped proxies for state capacity like GDP per capita and taxation as a percentage of GDP, which while informative, do not encompass the entirety of a state's capabilities. This thesis contributes to the existing literature on the topic of state capacity and disaster outcomes in five important ways: 1. Uses a comprehensive measure of stat capacity to gain more in depth insight into the role of the state apparatus on disaster-related outcomes; 2. Breaks down state capacity into three sub components to understand which aspects of state capacity impact outcomes; 3. Expands the discussion surrounding disaster outcomes to include medium and long-term components rather than simply immediate-term deaths; 4. Prioritizes the use of count models to explain death counts in order to understand the real life impacts of capacity; and 5. Arguably the most interesting addition, the use of a "deadliness" variable which contextualizes deaths by dividing them by the number of people affected by the disaster to understand the severity of the disaster.

My thesis utilizes regression analysis to explore the relationship between state capacity, its components and disaster-related outcomes: short-term deaths, length of time it takes for communities to rebuild, and the difference between the number of deaths in communities that have previously experienced a similar disaster. Chapter 3 explores the relationship between state capacity and deaths and deadliness in the immediate aftermath of a disaster, finding that greater state capacity is associated with fewer disaster-related deaths. These findings also largely held true for the sub-components of state capacity with administrative capacity being associated with the most significant negative relationships. Chapter 4 moves from the immediate term to the "medium term" or rebuilding period and focuses on the relationship between state capacity and resilience, or how quickly and effectively a community rebuilds. Chapter 4 finds a significant relationship between capacity and length of rebuilding, meaning that greater state capacity and administrative capacity is associated with a shorter rebuilding process, indicating greater resilience. Chapter 5 seeks to explain adaptive capacity or the ability of a nation to learn from past disasters and observes the relationship between state capacity and differences in disaster-related deaths and deadliness between first time disasters and communities experiencing a subsequent disaster. The results of this chapter are the most unclear with mostly insignificant results except for that between the "time since prior disaster" variable and log death difference, suggesting that subsequent disasters with longer time between the prior and subsequent disasters result in fewer relative deaths. 

I conclude that state capacity can and does play a crucial role in the immediate and medium-term following a disaster. The results for the long-term, or "building back better" outcome remain unclear and require further exploration.

Important to note, while many of the above results are statistically significant, it remains unclear as to whether they are practically significant and tangibly impact peoples lives. Results for logged outcome variables in this thesis tend to be more significant than those for the count data, suggesting that due to the distribution of the count data that linear models may not fully explain the variation in the data. One crucial area for future research involves expanding the use of count models for disaster-related death data. Due to the policy-related nature of this thesis and research question, it is important that while being answered in an academic context, results can be clearly communicated with non-academics. The use of count models for death data is especially important because it allows for researchers to provide a concrete number of lives that are associated with gains in capacity. Another limitation of this thesis is related to the assumptions necessitated by the fact that data needed to be joined with other data. This data limitation is best characterized by the imperfect merging technique used in Chapter 4 where I treat all aid projects that begin within a specified time period as being related to a given disaster. Both finer grain location data, and clearer explanations of the intent of aid projects would enable disasters and aid projects to be more easily linked and for greater certainty that the merged aid projects are actually rebuilding after the disasters that they are associated with in the dataset.

Another area for further exploration includes using machine learning and prediction techniques to test whether state capacity and its components can be used to predict disaster-related outcomes. This thesis focuses on explaining the variation that exists within the data. Using prediction techniques would not only be substantively interesting, but also could serve as an important tool for governments and policy makers to assess their vulnerability to disasters. 

Finally, while not a limitation, this paper solely employs quantitative techniques to answer the research question. Large-n studies are extremely useful and important for understanding generalizable trends and allow for some degree of statistical confidence, but do not take into account local and cultural dynamics that cannot be captured in a dataset. This study's purpose was not to understand the particular local dynamics of a state and how they relate to disaster-related outcomes but this information is still important and may provide clearer insight into what is happening in a particular country. The use of case studies, or particularly paired case studies could serve as a means to more qualitatively observe the relationship between state capacity and disaster-related outcomes.

Overall, this thesis seeks to expand the scope of the state capacity and disaster literature by prioritizing the use of both comprehensive and finer-grain measures of state capacity and different outcome variables, creating more practical and easy to interpret models and results. While economic indicators may be correlated with a nation's state capacity, the sole reliance on GDP per capita removes the nuance of state capacity from the equation, ultimately omitting crucial information. Through including finer-grain capacity indicators, areas for targeted improvement are more easily visible to states, allowing interested countries to prioritize improving an aspect of their state capacity in the hopes of increasing disaster resilience. Similarly, the expansion of outcome variables to include count variables and a measure of deadliness allows for results to be communicated in real-life terms. Ultimately, this thesis serves as a starting point both for understanding the relationship between state capacity, its components, and disaster-related outcomes.

\newpage

# Works Cited

