---
title: "Thesis - Version 1"
author: "Alexandra Norris"
date: "9/20/2021"
output:
  pdf_document:
    extra_dependencies: float
link_citations: yes
header-includes: \usepackage{setspace}\doublespacing\setlength{\parindent}{4em}\setlength{\parskip}{0em}
bibliography: references.bib
---

```{r setup, include=FALSE}

# The below code creates a bibliography and allows for the tables and figures to
# be placed where I want them to be

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")
knitr::write_bib(c("base", "tinytex", "knitr", "kableExtra", "latexpdf", "readtext", "utils", "stargazer", "tidyverse", "sandwich", "lfe", "grid", "RColorBrewer", "rgdal", "rgeos", "maptools", "seg", "splancs", "gridExtra"), "bibliography.bib", width = 60)

# load r packages

library(tinytex)
library(knitr)
library(kableExtra)
library(latexpdf)
library(readtext)
library(utils)
library(bookdown)

# need to load latex package "dcolumn" to allow latex tables to run and package
# "float" to place tables and figures where I want them to go

usepackage_latex("dcolumn")
usepackage_latex("float")

```

# Lit Review/Introduction

How do nations respond to natural disasters? What makes for an effective response and enables them to be more resilient than other nations?

The last twenty years have seen a significant rise in the number of climate-related disasters, putting much of the world’s population, in particular those living in poorer nations and communities at increased risk.  With Earth’s temperature predicted to rise further and with that the frequency of "once in a century" catastrophic weather events, the question of what enables nations to be resilient in the face of these exogenous disaster shocks is more important than ever.

[INSERT ANNECDOTES ABOUT NATIONS EXPERIENCING DISASTERS BUT WITH VASTLY DIFFERNT OUTCOMES TO HIGHLIGHT WHY THIS MATTERS]

Much scholarly work exists on the topic of natural disasters, but the focus has been largely on post-mortem assessments of disasters striking developed nations like the U.S.^[KATRINA LIT] and Japan^[@aldrich2015physical]. These assessments point to state capacity and social cohesion as the drivers responsible for effective disaster response and suggest that both the government and citizen responses play an important role.

Research on the developing world has mostly focused on individual and private sector responses to disasters^[@sawada2007impact, @drabo2015natural, @sawada2017natural, @rivera2014social], neglecting the roles that centralized states can play in disaster responses. This project builds on the work of @lin_governing_2015 which examines the relationship between the state and disaster vulnerability, finding evidence that democracy and strong state capacity reduce disaster-related mortality among citizens. Focusing not on disaster vulnerability, but instead disaster resilience, this project seeks to examine the rebuilding process following natural disasters in the developing world.  The following section defines natural disaster resilience and explores the factors that may influence how resilient a nation is.

# A Theory of Resilience

Informed by @cutter2008place, I define resilience as the ability of communities to respond quickly and efficiently to an exogenous disaster in a way in which future risk is reduced. In short, resilience is how capable communities are of “building back better”. 

## Operationalizing Resilience

Resilience, or building back better is comprised of both short and long-term components. Short term components include deaths and displaced people after the disaster as studied by @lin_governing_2015. Medium term components include the ability to rebuild homes, businesses, and crucial infrastructure. The long term component of resilience is "building back better", and includes the difficult to measure "ability to sustain a future disaster" variable.  This project mainly focusses on the medium-term rebuilding issues. In measuring resilience, I focus on two main vectors, 1) the government’s response to the disaster, and 2) how the people respond to the government’s response. 

I believe that resilience is determined by state capacity and inclusive institutions.

## Government Response

### State Capacity

State capacity, as defined by @hendrix2010 is a nation’s military capacity, bureaucratic/administrative capacity, and the quality of a nation’s political institutions. Military capacity contributes to state capacity in three distinct ways: as an example of a public good, as an indicator of taxation abilities, and repressive capacity.  @besley2009origins argue that the military is a public good and that investments in it are investments in the interests of all citizens and indicate the formation of a state.  @dincecco2019africa supports this argument when discussing the role of war, arguing that historical warfare indicates increased state capacity, but in the African context, this increased state capacity often manifests itself in the creation of special-interest states: states with high fiscal capacity and levels of civil-conflict.  This higher level of civil conflict is explained further by @robinson2002states who explains that warlords can arise when there is a strong military.  In that case, the military is still an indicator of state capacity, but instead of protecting from outside threats, it is used to stifle perceived internal threats.
 
The strength of the economy also plays a role in state capacity.  @besley2010state emphasize the symbiotic relationship between strong states and strong economies.  Richer states are able to provide services to their citizens which then ensure greater stability and revenue.  The converse of this is that poorer countries have less state capacity which leads to worse service allocation and increased poverty.  Poorer countries are more likely to engage in civil wars because the opportunity cost of foregoing being a law-abiding citizen is very low.  @hyden2012african supports this, arguing that governments want to grow the economy when they are dependent on the people for resources (TAXATION), creating a win-win relationship in which the economy grows and everyone has more money.  This inclusive growth of the economy can be contrasted with countries with vast natural resources.  In those nations, the economy isn’t tied to the welfare of the people and the state can gain resources and capacity without community benefit or buy-in. In order for a government to effectively extract resources from citizens through taxation there must be a reasonable state infrastructure set up.  There is also evidence that in fragile states, citizens engage more with the state when there is taxation^[@weigel2020participation]. 

In addition to the economy as it relates to the state, the economy on its own may also impact how a nation responds to a natural disaster.  Evidence from @garnett2010enhancing shows that in the aftermath of a 1998 flood in Bangladesh, the country’s free market allowed for grain to quickly be imported from abroad and was much faster than the government’s grain assistance. 

How responsive and ultimately resilient a  nation is after a natural disaster largely depends on the nation’s state capacity, or a government’s ability to control and govern its own territory. In the context of natural disaster resilience, state capacity allows for governments to take preventative action, respond to short-term results of crises -- rescues, medical care, shelter for the displaced -- and to facilitate the rebuilding of communities^[horney2018] . Without sufficient state capacity, even if political will exists, the government lacks the ability to follow through with effective action, leaving communities to their own devices to rebuild^[@skocpol1985]. 

**H1:** Greater state capacity will allow governments to be more resilient to exogenous natural disaster shocks.

### Bureaucratic Efficiency

Like state capacity more broadly, bureaucratic efficiency relies upon the effective functioning of the government, but instead of ability, it focuses on how quickly governments can execute a disaster response.  When a disaster strikes a community, there is an initial large disruption with people being displaced, infrastructure damaged, and overall panic. How quickly a community can begin rebuilding and ultimately recover from a disaster depends on how quickly systematic efforts are initiated to begin and carry out the recovery process. A more efficient bureaucracy allows for less “red tape” that can make rebuilding difficult and lengthy. @garnett2010enhancing in their assessment of states that responded effectively to natural disasters found that the decentralization of disaster response agencies allowed for more efficient responses and faster action after a hurricane in Honduras.  They also observed that the issuing of a time-sensitive emergency mandate in Mexico after an earthquake resulted in faster rebuilding. Both of these events show that prioritizing swift action can facilitate faster rebuilding after a disaster. Additionally, the Sendai Framework for Disaster Risk Reduction, the UN's framework for effective disaster response, encourages the decentralization of post-disaster governance to encourage local empowerment/investment and a swifter response^[@UN].

**H2:** Greater bureaucratic efficiency will result in greater resilience.

### Democracy and Disaster Response

@back2008democracy argue the existence of a j-shaped relationship between democracy and state capacity and that while a robust democracy has the most state capacity, authoritarian states have more than emerging democracies.  They argue that this is because of the strength of the bureaucracy.  Both authoritarian states and robust democracies are able to have strong bureaucracies, but they differ in where they derive their power.  Authoritarian states have a top-down structure governed by control and fear while strong democracies gain their power from public accountability, cooperation, and transparency.  Both are effective at promoting state capacity because they have the ability to control people – one through community buy-in and the other through fear/the ability to punish. @lin_governing_2015 finds evidence of a negative relationship between democracy and disaster mortality rates, suggesting that democratic regimes are better able to respond to and prepare for natural disasters. Interestingly, @lin_governing_2015 finds that voters typically prefer relief spending over spending on prevention, suggesting that the mechanism behind the relationship between democracy and disaster resilience is not due to political pressure to prepare for disasters but instead can potentially attributed to the government's relationship with and obligation to its citizens in the aftermath of the disaster.

This democratic accountability to a nation's citizens is largely a product of the principal-agent relationship. Ideally, elected politicians act in the best interests of their citizens, making decisions about disaster recovery on their behalf. Information asymmetry and clientelism are seemingly the largest forces that can pervert accountability.  Much literature suggests that when voters have information about politician preferences and performance^[@platas2019closing, @carlson2015ethnic] they are better able to vote for politicians that align with their beliefs.  Similarly, when given information about corruption or about the role of government, citizens (and in some cases government officials) are able to hold officials accountable through voting them out of office^[@ferraz2008exposing, @gottlieb2016greater, @blattman2019eat], and in the case of politicians controlling bureaucrats, increased oversight of budgets^[@raffler2016does].  Accountability also is impacted by clientelism, with vote buying in many cases perverting the principle-agent relationship so that politicians use citizens as agents to promote them to power^[@stokes2005perverse]. Regimes with robust democracies in which politicians are held accountable for their actions can be expected to facilitate more efficient recovery processes.

**H3:** Democratic regimes will enable affected communities to be more resilient

### Inclusive Institutions

Like democracy propper, another key component of resilience is how inclusive or democratic institutions are within a country. As defined by Acemoglu and Robinson (2012), inclusive institutions are economic and political systems which allow people to freely participate and benefit from the fruits of their labors.  Nations with inclusive institutions are characterized by sufficient state capacity^[Fukuyama 2011, 2014] but also by opportunities for citizens to participate in both the economy and politics in the ways that they deem best fit^[Acemoglu and Robinson 2016]. I hypothesize that countries with more inclusive institutions will be more resilient to natural disasters because a robust-free market economy and space already exists. When citizens are able to freely respond to what they perceive as the needs of themselves and their communities, overall disaster responses will be swifter^[@garnett2010enhancing]. Additionally, with private property protections, I expect citizens to be more inclined to initiate their own rebuilding process and may have greater access to capital with witch to make that happen.

**H4:** States with stronger private property rights and protections will be more resilient

## Citizens Responding to the Government Response 

While state capacity and political accountability determine what action a state will take in response to a natural disaster, many community dynamics play a role in how citizens respond both to the disaster itself and to government directives pertaining to the disaster.

### Community Involvement

Unlike the papers mentioned above in which citizens (principals) hold their politicians and governments (agents)  accountable through elections, in the case of disaster response, the time-line is much shorter, at least in the beginning, meaning that it is important to observe accountability not as an outcome in an experiment but as something embedded in the community. In addition to understanding how voters and people hold elected officials accountable, it is important to also understand how local people can feel empowered to support public works projects in their communities. @olken2010direct finds that local satisfaction with development projects was dramatically higher when the projects were chosen by way of direct votes from citizens rather than by choices made by a small group of people at a local meeting. @beath2017direcct and @beath2018can also support the importance of direct democracy, finding that aid projects in which all citizens were allowed to provide input for were more successful and representative of the needs of the people rather than just elites. These findings suggest that increased direct community involvement in disaster responses will help to make countries more resilient.  Findings from @garnett2010enhancing support this argument. In their analysis of a number of catastrophic environmental events, they found that initiatives that directly involved citizens in rebuilding after a disaster were more successful and efficient.

**H2.2:** Countries that prioritize local involvement in rebuilding will be more resilient

### Social Cohesion

While the actions of the government are important for how resilient a nation is to natural disasters, in order for things to be carried out and efficiently, there  must be cooperation both between the government and the people (trust, accountability, democracy) and between people (social cohesion). Aldrich and Meyer (2015) find that social capital and trust between the most vulnerable citizens and government officials is as important as the physical infrastructure rebuilding. When communities lack trust, they struggle to self organize and provide mutual aid to fellow citizens - this can result in less cooperation with relief and rebuilding projects^[Aldrich and Sawada 2015].
 
Especially salient in the developing world, ethnicity plays an important role in national cooperation and in the sense of a common identity.  @ostrom2007collective explains that the ability of a community to collectively act is largely determined by the number of people in the community, their ability to trust each other and work together, and in some circumstances, the heterogeneity of the community (part of the trust dynamic).  Ethnicity plays a large role in community trust but it is not completely clear what the shape of the relationship is.  There is evidence that more diversity actually improves the odds of collective action^[@posner2004political, @robinson2014national], but simultaneously, it is believed that increased diversity makes it more difficult for people to cooperate and decreases collective action^[@ejdemyr2018segregation, @habyarimana2007does].  I suspect that there may be a u-shaped relationship between diversity and collective action where homogeneous and extremely heterogeneous communities will both have higher levels of social-cohesion and are able to effectively act collectively while communities with one or a few dominant ethnic groups struggle more. 

Ethnicity is just one factor that can influence social cohesion, religion and income also play a role in social cohesion. @kawachi1997social find that smaller differences in income between people result in people viewing their social environments as less hostile and more hospitable. Much literature exists on the role of a middle class in economic development^[@banerjee2007economic, @birdsall2000stuck, @easterly2001middle] and in strengthening democratic institutions^[@fukuyama2012future], suggesting that a robust middle class both increases state capacity and social cohesion.

**H3:** Greater social cohesion will enable communities to be more resilient


## Price Gouging

Recovering and rebuilding after a natural disaster requires materials and tools. The question of price gouging is important for determining whether a nation's laws have created necessary, or at least helpful pre-conditions for effective recovery. While by nature of supply and demand building material prices should be expected to increase in the wake of a natural disaster, if the increase is too steep, people will not be able to afford to rebuild. There is no
set price level at which a price increase becomes gouging, it is genrally agreed that gouging occurs when prices rise to "unfair" levels^[@HBS]. 24 States in the United States currently have laws prohibiting price gouging^[@HBS] but their definitions vary by state with New Jersey for instance deeming a 10% price increase unlawful while Pennsylvania's legal limit is at a 20% increase over pre-disaster prices^[@Nationallawreview]. Because there is no set definition, to gauge whether price gouging is happening, I plan to look at price increases in the immediate aftermath of the disaster and compare the increases to previous fluctuations. Using the historical data, I will be able to see whether prices in the nation are just typically volatile or whether the increase following the disaster was different. If the increase is unprecedented, I will then observe the percentage increase in price to decide whether gouging occurred. Given the nebulous nature of price gouging, I think this may be an opportunity to employ a narrow and broad definition, likely at a 10% and 20% increase in price, using the variation in the US laws as a guide. 

To understand the role that price gouging plays or could play in disaster recovery, I plan to observe whether price controls pertaining to disasters or price controls more generally exist within a country and if they do, whether price trends indicate that these controls are being adhered to. I then plan to examine whether there is a relationship between price volatility and recovery to see if price controls are helpful.


\newpage


## Works Cited

